Return-Path: <linux-serial+bounces-7214-lists+linux-serial=lfdr.de@vger.kernel.org>
X-Original-To: lists+linux-serial@lfdr.de
Delivered-To: lists+linux-serial@lfdr.de
Received: from am.mirrors.kernel.org (am.mirrors.kernel.org [147.75.80.249])
	by mail.lfdr.de (Postfix) with ESMTPS id A74A09EE3F5
	for <lists+linux-serial@lfdr.de>; Thu, 12 Dec 2024 11:19:18 +0100 (CET)
Received: from smtp.subspace.kernel.org (relay.kernel.org [52.25.139.140])
	(using TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by am.mirrors.kernel.org (Postfix) with ESMTPS id B196D1888DCE
	for <lists+linux-serial@lfdr.de>; Thu, 12 Dec 2024 10:19:17 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id 6BF5E20FA82;
	Thu, 12 Dec 2024 10:19:13 +0000 (UTC)
X-Original-To: linux-serial@vger.kernel.org
Received: from smtp.gentoo.org (woodpecker.gentoo.org [140.211.166.183])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	by smtp.subspace.kernel.org (Postfix) with ESMTPS id 08EFD20E02C;
	Thu, 12 Dec 2024 10:19:11 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org; arc=none smtp.client-ip=140.211.166.183
ARC-Seal:i=1; a=rsa-sha256; d=subspace.kernel.org; s=arc-20240116;
	t=1733998753; cv=none; b=josOilj5MbC4I7aYQ/7tXrQ09yVsmutebR7E32pU94egNeS+X5nhrF6f18NLhk6wBCvhfn0mW72cdG0dmg2FACYtGCVUa+DcRpxQ3uZVhkKqIxUlADqDzdgmd5YiKSMw9+C8NDXVhu7g/0clsrTto/Z24+NwJkhTNi2LGT6wypM=
ARC-Message-Signature:i=1; a=rsa-sha256; d=subspace.kernel.org;
	s=arc-20240116; t=1733998753; c=relaxed/simple;
	bh=hnnh1ud49QqX1E1UbJ24ijhdVRhE3HXpcad8vHLOfbs=;
	h=Date:From:To:Cc:Subject:Message-ID:References:MIME-Version:
	 Content-Type:Content-Disposition:In-Reply-To; b=CeM2PrsKPbrZ9t2Ol8zv2MULlEoYvoj4RxJ59E94agGQTTL7bg9AqHdf0S/ofEo59OijUuzi4a3m0YjDhJP7N7hhUhUu0PmYvXT/iTqUS4fF/b4gyAOq1Y6FoON/VpwFgzVniYlX2gNgIMJJkYuAllwOzkeAyaJNPCaJBFHERwI=
ARC-Authentication-Results:i=1; smtp.subspace.kernel.org; dmarc=pass (p=none dis=none) header.from=gentoo.org; spf=pass smtp.mailfrom=gentoo.org; arc=none smtp.client-ip=140.211.166.183
Authentication-Results: smtp.subspace.kernel.org; dmarc=pass (p=none dis=none) header.from=gentoo.org
Authentication-Results: smtp.subspace.kernel.org; spf=pass smtp.mailfrom=gentoo.org
Date: Thu, 12 Dec 2024 18:19:01 +0800
From: Yixun Lan <dlan@gentoo.org>
To: Conor Dooley <conor.dooley@microchip.com>
Cc: linux-riscv@lists.infradead.org, robh@kernel.org, krzk+dt@kernel.org,
	conor+dt@kernel.org, paul.walmsley@sifive.com, palmer@dabbelt.com,
	aou@eecs.berkeley.edu, cyy@cyyself.name, daniel.lezcano@linaro.org,
	tglx@linutronix.de, samuel.holland@sifive.com, anup@brainfault.org,
	gregkh@linuxfoundation.org, jirislaby@kernel.org, lkundrak@v3.sk,
	devicetree@vger.kernel.org, linux-serial@vger.kernel.org,
	linux-kernel@vger.kernel.org, Jesse Taube <mr.bossman075@gmail.com>,
	inochiama@outlook.com, zhangmeng.kevin@spacemit.com,
	jszhang@kernel.org, matthias.bgg@kernel.org, kevin.z.m@hotmail.com
Subject: Re: [PATCH v5 00/10] riscv: add initial support for SpacemiT K1
Message-ID: <20241212101901-GYA2292414@gentoo>
References: <20240730-k1-01-basic-dt-v5-0-98263aae83be@gentoo.org>
 <173395638199.1729195.1529576042123666894.git-patchwork-notify@kernel.org>
Precedence: bulk
X-Mailing-List: linux-serial@vger.kernel.org
List-Id: <linux-serial.vger.kernel.org>
List-Subscribe: <mailto:linux-serial+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:linux-serial+unsubscribe@vger.kernel.org>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
In-Reply-To: <173395638199.1729195.1529576042123666894.git-patchwork-notify@kernel.org>

Hi Conor:

On 22:33 Wed 11 Dec     , patchwork-bot+linux-riscv@kernel.org wrote:
> Hello:
> 
> This series was applied to riscv/linux.git (fixes)
> by Conor Dooley <conor.dooley@microchip.com>:
> 
> On Tue, 30 Jul 2024 00:28:03 +0000 you wrote:
> > SpacemiT K1 is an ideal chip for some new extension such as RISC-V Vector
> > 1.0 and Zicond evaluation now. Add initial support for it to allow more
> > people to participate in building drivers to mainline for it.
> > 
> > This kernel has been tested upon Banana Pi BPI-F3 board on vendor U-Boot
> > bootflow generated by Armbian SDK[1] and patched OpenSBI[2] to enable
> > Zicboz, which does not in the vendor dts on its U-Boot. Then successfully
> > booted to busybox on initrd with this log[3].
> > 
> > [...]
> 
> Here is the summary with links:
>   - [v5,01/10] dt-bindings: vendor-prefixes: add spacemit
>     https://git.kernel.org/riscv/c/7cf3e9bfc63d
If I understand correctly, only patch [01/10] of this series was accepted
to 6.13-rc1

for the rest of patches, they would be expected to go through SpacemiT's
SoC tree? which should I take care of them.. so if no objection, I'd like to
queue them at branch k1/dt-for-next [1] first, we might rebase or revert if
something happens before merging (since the clock driver is still under review)

Let me know what you think..

Link: https://github.com/spacemit-com/linux/tree/k1/dt-for-next [1]
 

>   - [v5,02/10] dt-bindings: riscv: Add SpacemiT X60 compatibles
>     (no matching commit)
>   - [v5,03/10] dt-bindings: riscv: add SpacemiT K1 bindings
>     (no matching commit)
>   - [v5,04/10] dt-bindings: timer: Add SpacemiT K1 CLINT
>     (no matching commit)
>   - [v5,05/10] dt-bindings: interrupt-controller: Add SpacemiT K1 PLIC
>     (no matching commit)
>   - [v5,06/10] dt-bindings: serial: 8250: Add SpacemiT K1 uart compatible
>     (no matching commit)
>   - [v5,07/10] riscv: add SpacemiT SoC family Kconfig support
>     (no matching commit)
>   - [v5,08/10] riscv: dts: add initial SpacemiT K1 SoC device tree
>     (no matching commit)
>   - [v5,09/10] riscv: dts: spacemit: add Banana Pi BPI-F3 board device tree
>     (no matching commit)
>   - [v5,10/10] riscv: defconfig: enable SpacemiT SoC
>     (no matching commit)
> 
> You are awesome, thank you!
> -- 
> Deet-doot-dot, I am a bot.
> https://korg.docs.kernel.org/patchwork/pwbot.html
> 
> 

-- 
Yixun Lan (dlan)
Gentoo Linux Developer
GPG Key ID AABEFD55

